/**
 * Hero Block
 * @version 1.1.0 - 2026-01-17 - aspect-wide wrapper class propagation
 *
 * The hero block is auto-generated by buildHeroBlock() in scripts.js from default content.
 * This decorator handles the case when hero is explicitly authored as a block.
 *
 * == DA/EDS Table Structure ==
 * When authored as a block, the table has the block name "Hero" in the header row:
 *
 * | Hero                    |                           |
 * |-------------------------|---------------------------|
 * | [image]                 | Headline text             |
 * |                         | Subheadline text          |
 * |                         | [CTA button link]         |
 *
 * This converts to HTML:
 * <div class="hero">
 *   <div>  <!-- row -->
 *     <div><picture>...</picture></div>  <!-- image cell -->
 *     <div>                              <!-- content cell -->
 *       <h1>Headline</h1>
 *       <p>Subheadline</p>
 *       <p><a href="..." class="button">CTA</a></p>
 *     </div>
 *   </div>
 * </div>
 *
 * == Default Content (Auto-blocked) ==
 * When not authored as a block table, hero is auto-created from:
 * <p><picture>...</picture></p>
 * <h1>Headline</h1>
 *
 * The buildHeroBlock() function in scripts.js detects this pattern and wraps it.
 */

export default function decorate(block) {
  // Mark first cell with image as the image column
  const firstRow = block.firstElementChild;
  if (firstRow) {
    const cells = [...firstRow.children];
    cells.forEach((cell) => {
      const pic = cell.querySelector('picture');
      if (pic && cell.children.length === 1) {
        cell.classList.add('hero-image');
      } else if (cell.querySelector('h1') || cell.textContent.trim()) {
        cell.classList.add('hero-content');
      }
    });
  }

  // Remove any CTA buttons from hero
  const ctaButton = block.querySelector('.button-container');
  if (ctaButton) {
    ctaButton.remove();
  }

  // For aspect-wide heroes, propagate class to wrapper and section for full-width styling
  // This ensures the wrapper max-width and section padding are overridden without relying on :has()
  if (block.classList.contains('aspect-wide')) {
    const wrapper = block.closest('.hero-wrapper');
    // eslint-disable-next-line no-console
    console.log('[Hero] aspect-wide detected, wrapper:', wrapper?.className);
    if (wrapper) {
      wrapper.classList.add('aspect-wide-wrapper');
    }
    const section = block.closest('.hero-container');
    if (section) {
      section.classList.add('aspect-wide-section');
    }
  }
}
